name: 'Trivy - Multi-purpose Security Scanner'
description: 'Scan filesystem, containers, IaC, and secrets using Trivy (language-agnostic)'

inputs:
  scan-type:
    description: 'Type of scan (fs, image, config)'
    required: false
    default: 'fs'
  severity:
    description: 'Severities to scan (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
    default: 'HIGH,CRITICAL'
  scan-path:
    description: 'Path to scan (. for current directory, or image name for container scan)'
    required: false
    default: '.'
  exit-code:
    description: 'Exit code when vulnerabilities found (0 or 1)'
    required: false
    default: '1'
  format:
    description: 'Output format (table, json, sarif)'
    required: false
    default: 'sarif'
  skip-dirs:
    description: 'Comma-separated directories to skip (e.g., node_modules,vendor)'
    required: false
    default: 'node_modules,dist,build,.git'

runs:
  using: 'composite'
  steps:
    - name: '[ACTION] Trivy scan - Info'
      shell: bash
      run: |
        echo "🔍 [Trivy] Starting multi-purpose security scan..."
        echo "   Scan type: ${{ inputs.scan-type }}"
        echo "   Severity: ${{ inputs.severity }}"
        echo "   Scan path: ${{ inputs.scan-path }}"
        echo "   Skip dirs: ${{ inputs.skip-dirs }}"

    - name: '[ACTION] Run Trivy scan'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: ${{ inputs.scan-type }}
        scan-ref: ${{ inputs.scan-path }}
        severity: ${{ inputs.severity }}
        exit-code: '0'  # Always pass - we'll analyze after
        format: ${{ inputs.format }}
        output: 'trivy-results.sarif'
        skip-dirs: ${{ inputs.skip-dirs }}
      env:
        TRIVY_TIMEOUT: '10m'
    
    - name: '[ACTION] Analyze Trivy results - Filter transitive dependencies'
      if: always()
      shell: bash
      run: |
        echo ""
        echo "📊 [Trivy] Analyzing scan results..."
        
        if [ ! -f "trivy-results.sarif" ]; then
          echo "⚠️  No SARIF file generated"
          exit 0
        fi
        
        # Check if jq is available
        if ! command -v jq &> /dev/null; then
          echo "⚠️  jq not found - cannot filter transitive dependencies"
          echo "   Installing vulnerabilities as-is"
          if [ "${{ inputs.exit-code }}" = "1" ]; then
            # Check if there are any results
            RESULT_COUNT=$(jq -r '.runs[0].results | length' trivy-results.sarif 2>/dev/null || echo "0")
            if [ "$RESULT_COUNT" -gt 0 ]; then
              echo "❌ Found $RESULT_COUNT vulnerability/vulnerabilities"
              exit 1
            fi
          fi
          exit 0
        fi
        
        # Extract vulnerability locations from SARIF
        TOTAL_VULNS=$(jq -r '.runs[0].results | length' trivy-results.sarif 2>/dev/null || echo "0")
        
        if [ "$TOTAL_VULNS" -eq 0 ]; then
          echo "✅ [Trivy] No vulnerabilities found"
          exit 0
        fi
        
        echo "🔍 Found $TOTAL_VULNS total vulnerability/vulnerabilities"
        echo ""
        
        # Analyze each vulnerability location
        DIRECT_VULNS=0
        TRANSITIVE_VULNS=0
        declare -a DIRECT_PACKAGES=()
        declare -a TRANSITIVE_PACKAGES=()
        
        # Check if vulnerabilities are in pnpm-lock.yaml or package-lock.json (transitive)
        # vs direct package.json dependencies
        while IFS='|' read -r location package_name severity; do
          if [ -z "$location" ]; then
            continue
          fi
          
          if [[ "$location" == *"lock.yaml"* ]] || [[ "$location" == *"package-lock.json"* ]]; then
            # Check if it's a deep transitive dependency
            # For pnpm/npm lockfiles, all deps appear there, but we need to check package.json
            TRANSITIVE_VULNS=$((TRANSITIVE_VULNS + 1))
            TRANSITIVE_PACKAGES+=("$package_name ($severity)")
          else
            DIRECT_VULNS=$((DIRECT_VULNS + 1))
            DIRECT_PACKAGES+=("$package_name ($severity)")
          fi
        done < <(jq -r '.runs[0].results[] | (.locations[].physicalLocation.artifactLocation.uri + "|" + (.message.text | capture("Package: (?<pkg>[^\n]+)").pkg) + "|" + (.level | ascii_upcase))' trivy-results.sarif 2>/dev/null || echo "")
        
        # For filesystem scans, vulnerabilities in lockfiles are typically transitive
        # Check if we have package.json to compare
        if [ -f "package.json" ] && [ $TRANSITIVE_VULNS -gt 0 ]; then
          echo "📦 Detected lockfile vulnerabilities - checking if transitive..."
          
          # Extract unique package names from Trivy results
          VULN_PACKAGES=$(jq -r '.runs[0].results[].message.text' trivy-results.sarif 2>/dev/null | grep "Package:" | sed 's/Package: //' | sort -u)
          
          # Check if any vulnerable package is in direct dependencies
          FOUND_DIRECT=false
          RECLASSIFIED=0
          while IFS= read -r pkg; do
            if [ -n "$pkg" ] && grep -q "\"$pkg\"" package.json 2>/dev/null; then
              echo "⚠️  Package '$pkg' is a DIRECT dependency"
              FOUND_DIRECT=true
              DIRECT_VULNS=$((DIRECT_VULNS + 1))
              TRANSITIVE_VULNS=$((TRANSITIVE_VULNS - 1))
              RECLASSIFIED=$((RECLASSIFIED + 1))
              
              # Move from transitive to direct list
              for i in "${!TRANSITIVE_PACKAGES[@]}"; do
                if [[ "${TRANSITIVE_PACKAGES[$i]}" == "$pkg"* ]]; then
                  DIRECT_PACKAGES+=("${TRANSITIVE_PACKAGES[$i]}")
                  unset 'TRANSITIVE_PACKAGES[$i]'
                  break
                fi
              done
            fi
          done <<< "$VULN_PACKAGES"
          
          if [ "$FOUND_DIRECT" = false ]; then
            echo "✅ All vulnerable packages are TRANSITIVE dependencies"
          fi
        fi
        
        echo ""
        echo "📊 Analysis Summary:"
        echo "   Total vulnerabilities: $TOTAL_VULNS"
        echo "   Direct dependencies: $DIRECT_VULNS"
        echo "   Transitive dependencies: $TRANSITIVE_VULNS"
        echo ""
        
        # Decision logic
        if [ $DIRECT_VULNS -eq 0 ] && [ $TRANSITIVE_VULNS -gt 0 ]; then
          echo "⚠️  WARNING: All vulnerabilities are in TRANSITIVE dependencies"
          echo ""
          echo "📊 Transitive Dependencies with Security Issues: $TRANSITIVE_VULNS"
          if [ ${#TRANSITIVE_PACKAGES[@]} -gt 0 ]; then
            echo "   Affected packages:"
            # Remove duplicates and print
            printf '%s\n' "${TRANSITIVE_PACKAGES[@]}" | sort -u | while read -r pkg; do
              [ -n "$pkg" ] && echo "     - $pkg"
            done
          fi
          echo ""
          echo "💡 These come from nested dependencies. Monitor for upstream fixes."
          echo ""
          echo "✅ Pipeline will PASS (no direct dependency vulnerabilities)"
          exit 0
        elif [ $DIRECT_VULNS -gt 0 ]; then
          echo "🚨 CRITICAL: Security vulnerabilities detected!"
          echo ""
          
          if [ $DIRECT_VULNS -gt 0 ]; then
            echo "📊 Direct Dependencies with Security Issues: $DIRECT_VULNS"
            if [ ${#DIRECT_PACKAGES[@]} -gt 0 ]; then
              echo "   Affected packages:"
              printf '%s\n' "${DIRECT_PACKAGES[@]}" | sort -u | while read -r pkg; do
                [ -n "$pkg" ] && echo "     - $pkg"
              done
            fi
            echo ""
          fi
          
          if [ $TRANSITIVE_VULNS -gt 0 ]; then
            echo "📊 Transitive Dependencies with Security Issues: $TRANSITIVE_VULNS"
            if [ ${#TRANSITIVE_PACKAGES[@]} -gt 0 ]; then
              echo "   Affected packages:"
              printf '%s\n' "${TRANSITIVE_PACKAGES[@]}" | sort -u | while read -r pkg; do
                [ -n "$pkg" ] && echo "     - $pkg"
              done
            fi
            echo ""
          fi
          
          echo "❌ Pipeline will FAIL - please update your direct dependencies"
          echo ""
          if [ "${{ inputs.exit-code }}" = "1" ]; then
            exit 1
          fi
        else
          echo "✅ [Trivy] No vulnerabilities found"
          exit 0
        fi

    # GitHub Advanced Security (code scanning) é necessário para upload de SARIF
    # Para repositórios privados, isso é um recurso PAGO
    # Para repositórios públicos, é GRÁTIS
    # Descomente abaixo se você tiver Advanced Security habilitado:
    # - name: '[ACTION] Upload SARIF to GitHub Security'
    #   if: always() && inputs.format == 'sarif'
    #   uses: github/codeql-action/upload-sarif@v4
    #   with:
    #     sarif_file: 'trivy-results.sarif'
    #     category: trivy-${{ inputs.scan-type }}
    #   continue-on-error: true

    - name: '[ACTION] Upload Trivy report artifact'
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-${{ inputs.scan-type }}-report-${{ github.sha }}
        path: trivy-results.sarif
        retention-days: 30
        if-no-files-found: ignore
