name: 'Semgrep CE - SAST Scan'
description: 'Static Application Security Testing using Semgrep Community Edition (language-agnostic)'

inputs:
  config:
    description: 'Semgrep config (auto, p/security-audit, p/owasp-top-ten, p/ci, p/default)'
    required: false
    default: 'auto'
  severity:
    description: 'Minimum severity to report (INFO, WARNING, ERROR)'
    required: false
    default: 'WARNING'
  continue-on-error:
    description: 'Continue pipeline even if findings detected'
    required: false
    default: 'false'
  scan-path:
    description: 'Path to scan (defaults to current directory)'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: '[ACTION] Run Semgrep scan'
      shell: bash
      run: |
        echo "🔍 [Semgrep] Starting SAST scan..."
        echo "   Config: ${{ inputs.config }}"
        echo "   Severity: ${{ inputs.severity }}"
        echo "   Scan path: ${{ inputs.scan-path }}"
      
    - name: '[ACTION] Setup Python for Semgrep'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: '[ACTION] Cache pip dependencies'
      id: cache-semgrep
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-semgrep-1.144.0
        restore-keys: |
          ${{ runner.os }}-pip-semgrep-

    - name: '[ACTION] Install Semgrep'
      shell: bash
      run: |
        pip install semgrep==1.144.0
        semgrep --version    - name: '[ACTION] Execute Semgrep'
      shell: bash
      run: |
        set +e
        semgrep scan \
          --config=${{ inputs.config }} \
          --sarif \
          --output=semgrep.sarif \
          ${{ inputs.scan-path }}
        EXIT_CODE=$?
        set -e
        
        if [ $EXIT_CODE -ne 0 ] && [ "${{ inputs.continue-on-error }}" = "false" ]; then
          echo "❌ [Semgrep] Findings detected (exit code: $EXIT_CODE)"
          exit $EXIT_CODE
        elif [ $EXIT_CODE -ne 0 ]; then
          echo "⚠️ [Semgrep] Findings detected but continuing (continue-on-error=true)"
        else
          echo "✅ [Semgrep] No findings"
        fi

    # GitHub Advanced Security (code scanning) é necessário para upload de SARIF
    # Para repositórios privados, isso é um recurso PAGO
    # Para repositórios públicos, é GRÁTIS
    # Descomente abaixo se você tiver Advanced Security habilitado:
    # - name: '[ACTION] Upload SARIF to GitHub Security'
    #   if: always()
    #   uses: github/codeql-action/upload-sarif@v4
    #   with:
    #     sarif_file: semgrep.sarif
    #     category: semgrep
    #   continue-on-error: true

    - name: '[ACTION] Upload Semgrep report artifact'
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report-${{ github.sha }}
        path: semgrep.sarif
        retention-days: 30
        if-no-files-found: ignore
