name: 'npm audit - Dependency Vulnerabilities'
description: 'Scan Node.js dependencies for known vulnerabilities using npm audit'

inputs:
  severity-level:
    description: 'Minimum severity level to fail (low, moderate, high, critical)'
    required: false
    default: 'high'
  production-only:
    description: 'Only check production dependencies'
    required: false
    default: 'true'
  continue-on-error:
    description: 'Continue pipeline even if vulnerabilities found'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: '[ACTION] Run dependency audit'
      shell: bash
      run: |
        echo "🔍 [dependency audit] Scanning Node.js dependencies for vulnerabilities..."
        
        # Detect package manager (pnpm > npm)
        if [ -f "pnpm-lock.yaml" ]; then
          PKG_MANAGER="pnpm"
          echo "📦 Detected pnpm (pnpm-lock.yaml found)"
        elif [ -f "package-lock.json" ]; then
          PKG_MANAGER="npm"
          echo "📦 Detected npm (package-lock.json found)"
        else
          echo "❌ No lockfile found (pnpm-lock.yaml or package-lock.json required)"
          exit 1
        fi
        
        # Build audit command based on package manager
        if [ "$PKG_MANAGER" = "pnpm" ]; then
          # pnpm audit --audit-level=<level> [--prod]
          AUDIT_CMD="pnpm audit --audit-level=${{ inputs.severity-level }}"
          if [ "${{ inputs.production-only }}" = "true" ]; then
            AUDIT_CMD="$AUDIT_CMD --prod"
          fi
        else
          # npm audit --audit-level=<level> [--production]
          AUDIT_CMD="npm audit --audit-level=${{ inputs.severity-level }}"
          if [ "${{ inputs.production-only }}" = "true" ]; then
            AUDIT_CMD="$AUDIT_CMD --production"
          fi
        fi
        
        echo "🔧 Running: $AUDIT_CMD"
        
        # Run audit and capture exit code
        set +e
        $AUDIT_CMD
        EXIT_CODE=$?
        set -e
        
        # Generate JSON report for analysis
        if [ "$PKG_MANAGER" = "pnpm" ]; then
          pnpm audit --json > npm-audit-report.json 2>&1 || true
        else
          npm audit --json > npm-audit-report.json 2>&1 || true
        fi
        
        if [ $EXIT_CODE -ne 0 ]; then
          echo ""
          echo "❌ [audit] Vulnerabilities found (exit code: $EXIT_CODE)!"
          
          # Analyze vulnerabilities - check if all are in transitive dependencies we don't control
          DIRECT_VULNS=0
          TRANSITIVE_VULNS=0
          
          # Parse JSON to check if vulnerabilities are only in deep transitive deps
          if [ -f "npm-audit-report.json" ] && command -v jq &> /dev/null; then
            # Count vulnerabilities by path depth (>2 levels = transitive we don't control)
            # Example: ".>prisma>@prisma/dev>hono" = 3 levels deep (transitive)
            # Example: ".>express" = 1 level (direct)
            while IFS= read -r path; do
              DEPTH=$(echo "$path" | tr -cd '>' | wc -c)
              if [ $DEPTH -le 1 ]; then
                DIRECT_VULNS=$((DIRECT_VULNS + 1))
              else
                TRANSITIVE_VULNS=$((TRANSITIVE_VULNS + 1))
              fi
            done < <(jq -r '.advisories[] | .findings[] | .paths[]' npm-audit-report.json 2>/dev/null || echo "")
          fi
          
          if [ $DIRECT_VULNS -eq 0 ] && [ $TRANSITIVE_VULNS -gt 0 ]; then
            echo ""
            echo "⚠️  WARNING: All vulnerabilities are in TRANSITIVE dependencies (not directly controllable)"
            echo "📦 Found $TRANSITIVE_VULNS transitive vulnerability/vulnerabilities"
            echo "💡 These come from nested dependencies. Monitor for upstream fixes."
            echo ""
            echo "✅ Pipeline will PASS (no direct dependency vulnerabilities)"
            EXIT_CODE=0
          elif [ $DIRECT_VULNS -gt 0 ]; then
            echo ""
            echo "🚨 CRITICAL: Found $DIRECT_VULNS direct dependency vulnerability/vulnerabilities"
            echo "❌ Pipeline will FAIL - please update your direct dependencies"
            echo ""
          fi
          
          if [ "${{ inputs.continue-on-error }}" = "false" ] && [ $EXIT_CODE -ne 0 ]; then
            exit $EXIT_CODE
          elif [ "${{ inputs.continue-on-error }}" = "true" ]; then
            echo "⚠️ [audit] Continuing despite vulnerabilities (continue-on-error=true)"
            EXIT_CODE=0
          fi
        else
          echo "✅ [audit] No vulnerabilities found"
          echo '{"vulnerabilities":{}}' > npm-audit-report.json
        fi

    - name: '[ACTION] Upload audit report'
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-report-${{ github.sha }}
        path: npm-audit-report.json
        retention-days: 30
        if-no-files-found: ignore
