name: 'npm audit - Dependency Vulnerabilities'
description: 'Scan Node.js dependencies for known vulnerabilities using npm audit'

inputs:
  severity-level:
    description: 'Minimum severity level to fail (low, moderate, high, critical)'
    required: false
    default: 'high'
  production-only:
    description: 'Only check production dependencies'
    required: false
    default: 'true'
  continue-on-error:
    description: 'Continue pipeline even if vulnerabilities found'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: '[ACTION] Run dependency audit'
      shell: bash
      run: |
        echo "🔍 [dependency audit] Scanning Node.js dependencies for vulnerabilities..."
        
        # Detect package manager (pnpm > npm)
        if [ -f "pnpm-lock.yaml" ]; then
          PKG_MANAGER="pnpm"
          echo "📦 Detected pnpm (pnpm-lock.yaml found)"
        elif [ -f "package-lock.json" ]; then
          PKG_MANAGER="npm"
          echo "📦 Detected npm (package-lock.json found)"
        else
          echo "❌ No lockfile found (pnpm-lock.yaml or package-lock.json required)"
          exit 1
        fi
        
        # Build audit command based on package manager
        if [ "$PKG_MANAGER" = "pnpm" ]; then
          # pnpm audit --audit-level=<level> [--prod]
          AUDIT_CMD="pnpm audit --audit-level=${{ inputs.severity-level }}"
          if [ "${{ inputs.production-only }}" = "true" ]; then
            AUDIT_CMD="$AUDIT_CMD --prod"
          fi
        else
          # npm audit --audit-level=<level> [--production]
          AUDIT_CMD="npm audit --audit-level=${{ inputs.severity-level }}"
          if [ "${{ inputs.production-only }}" = "true" ]; then
            AUDIT_CMD="$AUDIT_CMD --production"
          fi
        fi
        
        echo "🔧 Running: $AUDIT_CMD"
        
        # Run audit and capture exit code
        set +e
        $AUDIT_CMD
        EXIT_CODE=$?
        set -e
        
        if [ $EXIT_CODE -ne 0 ]; then
          echo "❌ [audit] Vulnerabilities found (exit code: $EXIT_CODE)!"
          
          # Generate JSON report for artifact
          if [ "$PKG_MANAGER" = "pnpm" ]; then
            pnpm audit --json > npm-audit-report.json 2>&1 || true
          else
            npm audit --json > npm-audit-report.json 2>&1 || true
          fi
          
          if [ "${{ inputs.continue-on-error }}" = "false" ]; then
            exit $EXIT_CODE
          else
            echo "⚠️ [audit] Continuing despite vulnerabilities (continue-on-error=true)"
          fi
        else
          echo "✅ [audit] No vulnerabilities found"
          # Create empty report for consistency
          echo '{"vulnerabilities":{}}' > npm-audit-report.json
        fi

    - name: '[ACTION] Upload audit report'
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-report-${{ github.sha }}
        path: npm-audit-report.json
        retention-days: 30
        if-no-files-found: ignore
