name: "🔧 Setup Go"
description: "Setup Go com cache de módulos"

inputs:
  go-version:
    description: "Versão do Go (ex: 1.22, 1.21)"
    required: false
    default: "1.22"

runs:
  using: "composite"
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
